### ISSUE TITLE
Fill out readme

### ISSUE THREAD

**Issue by JohnTrapp** [JohnTrapp/python-tdd-example#4]
The readme is default right now, so let's put in some stuff.

## Requirements
- [ ] Change file mention in `setup.cgf` to `file:README.md`
- [ ] Add introduction
- [ ] Add how to build/test
- [ ] Add how to modify to be a starting template
- [ ] Add explanation of GitHub Actions
- [ ] Add explication of recommended GitHub settings
- [ ] Add some useful links
